import type { TreatmentProduct } from "@/lib/types/domain";

/**
 * 카테고리 상품 리스트/상세 페이지에서 사용되는 시술 상품 더미 데이터.
 * categoryId/hospitalId는 categories.ts/hospitals.ts에 정의된 id와 참조 무결성을 유지한다.
 * 이미지 URL은 실제 자산 없이 placeholder 경로 문자열만 사용한다.
 */
export const dummyProducts: TreatmentProduct[] = [
  {
    id: "prod-1",
    categoryId: "cat-1",
    hospitalId: "hosp-1",
    name: "수분 물광 리프팅 시술",
    originalPrice: 300000,
    discountPrice: 199000,
    includesVat: true,
    includesAnesthesia: false,
    includesAftercare: true,
    sideEffectNotice:
      "시술 부위에 일시적인 붉어짐이나 미세한 붓기가 있을 수 있습니다.",
    thumbnailUrl: "/placeholder-product-1.jpg",
    detailImageUrls: [
      "/placeholder-detail-1-1.jpg",
      "/placeholder-detail-1-2.jpg",
    ],
  },
  {
    id: "prod-2",
    categoryId: "cat-1",
    hospitalId: "hosp-5",
    name: "듀얼 토닝 피부 재생 레이저",
    originalPrice: 250000,
    discountPrice: 149000,
    includesVat: true,
    includesAnesthesia: false,
    includesAftercare: true,
    sideEffectNotice:
      "시술 직후 일시적인 홍조가 나타날 수 있으며 자외선 차단이 필요합니다.",
    thumbnailUrl: "/placeholder-product-2.jpg",
    detailImageUrls: ["/placeholder-detail-2-1.jpg"],
  },
  {
    id: "prod-3",
    categoryId: "cat-2",
    hospitalId: "hosp-2",
    name: "자연유착 쌍꺼풀 수술",
    originalPrice: 1500000,
    discountPrice: 990000,
    includesVat: true,
    includesAnesthesia: true,
    includesAftercare: true,
    sideEffectNotice: "수술 후 1~2주간 붓기 및 멍이 발생할 수 있습니다.",
    thumbnailUrl: "/placeholder-product-3.jpg",
    detailImageUrls: [
      "/placeholder-detail-3-1.jpg",
      "/placeholder-detail-3-2.jpg",
    ],
  },
  {
    id: "prod-4",
    categoryId: "cat-2",
    hospitalId: "hosp-4",
    name: "눈매교정 절개 수술",
    originalPrice: 2200000,
    discountPrice: 1690000,
    includesVat: true,
    includesAnesthesia: true,
    includesAftercare: true,
    sideEffectNotice: "개인차에 따라 회복 기간이 2~4주 소요될 수 있습니다.",
    thumbnailUrl: "/placeholder-product-4.jpg",
    detailImageUrls: ["/placeholder-detail-4-1.jpg"],
  },
  {
    id: "prod-5",
    categoryId: "cat-3",
    hospitalId: "hosp-2",
    name: "코끝 성형 실리콘 보형물 수술",
    originalPrice: 2800000,
    discountPrice: 2190000,
    includesVat: true,
    includesAnesthesia: true,
    includesAftercare: true,
    sideEffectNotice:
      "수술 부위 부기가 완전히 빠지기까지 약 1개월이 소요될 수 있습니다.",
    thumbnailUrl: "/placeholder-product-5.jpg",
    detailImageUrls: ["/placeholder-detail-5-1.jpg"],
  },
  {
    id: "prod-6",
    categoryId: "cat-4",
    hospitalId: "hosp-4",
    name: "사각턱 보톡스 윤곽 시술",
    originalPrice: 200000,
    discountPrice: 99000,
    includesVat: true,
    includesAnesthesia: false,
    includesAftercare: false,
    sideEffectNotice: "일시적인 저작 시 불편감이 있을 수 있습니다.",
    thumbnailUrl: "/placeholder-product-6.jpg",
    detailImageUrls: ["/placeholder-detail-6-1.jpg"],
  },
  {
    id: "prod-7",
    categoryId: "cat-5",
    hospitalId: "hosp-3",
    name: "코헤시브 가슴성형 수술",
    originalPrice: 8000000,
    discountPrice: 6500000,
    includesVat: true,
    includesAnesthesia: true,
    includesAftercare: true,
    sideEffectNotice: "수술 후 정기적인 경과 관찰이 필요합니다.",
    thumbnailUrl: "/placeholder-product-7.jpg",
    detailImageUrls: ["/placeholder-detail-7-1.jpg"],
  },
  {
    id: "prod-8",
    categoryId: "cat-6",
    hospitalId: "hosp-6",
    name: "복부 지방흡입 바디라인 시술",
    originalPrice: 3500000,
    discountPrice: 2790000,
    includesVat: true,
    includesAnesthesia: true,
    includesAftercare: true,
    sideEffectNotice: "시술 후 압박복 착용 등 관리 지침 준수가 필요합니다.",
    thumbnailUrl: "/placeholder-product-8.jpg",
    detailImageUrls: ["/placeholder-detail-8-1.jpg"],
  },
  {
    id: "prod-9",
    categoryId: "cat-7",
    hospitalId: "hosp-1",
    name: "이마 보톡스 주름 개선 시술",
    originalPrice: 150000,
    discountPrice: 79000,
    includesVat: true,
    includesAnesthesia: false,
    includesAftercare: false,
    sideEffectNotice: "드물게 두통이나 멍이 발생할 수 있습니다.",
    thumbnailUrl: "/placeholder-product-9.jpg",
    detailImageUrls: ["/placeholder-detail-9-1.jpg"],
  },
  {
    id: "prod-10",
    categoryId: "cat-7",
    hospitalId: "hosp-8",
    name: "볼륨 히알루론산 필러",
    originalPrice: 350000,
    discountPrice: 259000,
    includesVat: true,
    includesAnesthesia: false,
    includesAftercare: false,
    sideEffectNotice: "시술 부위 붓기 및 멍이 며칠간 지속될 수 있습니다.",
    thumbnailUrl: "/placeholder-product-10.jpg",
    detailImageUrls: ["/placeholder-detail-10-1.jpg"],
  },
  {
    id: "prod-11",
    categoryId: "cat-8",
    hospitalId: "hosp-3",
    name: "실 리프팅 탄력 개선 시술",
    originalPrice: 900000,
    discountPrice: 590000,
    includesVat: true,
    includesAnesthesia: true,
    includesAftercare: true,
    sideEffectNotice: "시술 부위 당김감이 1~2주간 지속될 수 있습니다.",
    thumbnailUrl: "/placeholder-product-11.jpg",
    detailImageUrls: ["/placeholder-detail-11-1.jpg"],
  },
  {
    id: "prod-12",
    categoryId: "cat-9",
    hospitalId: "hosp-7",
    name: "레이저 제모 전신 패키지",
    originalPrice: 600000,
    discountPrice: 299000,
    includesVat: true,
    includesAnesthesia: false,
    includesAftercare: false,
    sideEffectNotice: "시술 직후 일시적 홍반이 나타날 수 있습니다.",
    thumbnailUrl: "/placeholder-product-12.jpg",
    detailImageUrls: ["/placeholder-detail-12-1.jpg"],
  },
  {
    id: "prod-17",
    categoryId: "cat-9",
    hospitalId: "hosp-3",
    name: "고주파 부분 제모 시술",
    originalPrice: 250000,
    discountPrice: 129000,
    includesVat: true,
    includesAnesthesia: false,
    includesAftercare: false,
    sideEffectNotice:
      "시술 부위에 일시적인 따끔거림이나 붉어짐이 있을 수 있습니다.",
    thumbnailUrl: "/placeholder-product-17.jpg",
    detailImageUrls: ["/placeholder-detail-17-1.jpg"],
  },
  {
    id: "prod-18",
    categoryId: "cat-9",
    hospitalId: "hosp-8",
    name: "니들 제모 정밀 관리 패키지",
    originalPrice: 450000,
    discountPrice: 259000,
    includesVat: true,
    includesAnesthesia: true,
    includesAftercare: true,
    sideEffectNotice: "시술 후 모낭 주변 붉은기가 며칠간 지속될 수 있습니다.",
    thumbnailUrl: "/placeholder-product-18.jpg",
    detailImageUrls: ["/placeholder-detail-18-1.jpg"],
  },
  {
    id: "prod-13",
    categoryId: "cat-10",
    hospitalId: "hosp-2",
    name: "모발이식 M자 탈모 개선술",
    originalPrice: 4500000,
    discountPrice: 3490000,
    includesVat: true,
    includesAnesthesia: true,
    includesAftercare: true,
    sideEffectNotice: "이식 부위 딱지 및 일시적 통증이 발생할 수 있습니다.",
    thumbnailUrl: "/placeholder-product-13.jpg",
    detailImageUrls: ["/placeholder-detail-13-1.jpg"],
  },
  {
    id: "prod-14",
    categoryId: "cat-11",
    hospitalId: "hosp-8",
    name: "치아미백 스케일링 패키지",
    originalPrice: 180000,
    discountPrice: 99000,
    includesVat: true,
    includesAnesthesia: false,
    includesAftercare: false,
    sideEffectNotice: "시술 후 일시적으로 시린 느낌이 있을 수 있습니다.",
    thumbnailUrl: "/placeholder-product-14.jpg",
    detailImageUrls: ["/placeholder-detail-14-1.jpg"],
  },
  {
    id: "prod-15",
    categoryId: "cat-12",
    hospitalId: "hosp-5",
    name: "울쎄라 안티에이징 시술",
    originalPrice: 1200000,
    discountPrice: 890000,
    includesVat: true,
    includesAnesthesia: false,
    includesAftercare: true,
    sideEffectNotice: "시술 중 일시적인 열감과 통증이 있을 수 있습니다.",
    thumbnailUrl: "/placeholder-product-15.jpg",
    detailImageUrls: ["/placeholder-detail-15-1.jpg"],
  },
  {
    id: "prod-16",
    categoryId: "cat-12",
    hospitalId: "hosp-6",
    name: "인모드 탄력 안티에이징 리프팅",
    originalPrice: 800000,
    discountPrice: 550000,
    includesVat: true,
    includesAnesthesia: false,
    includesAftercare: true,
    sideEffectNotice: "시술 부위 일시적인 열감이 있을 수 있습니다.",
    thumbnailUrl: "/placeholder-product-16.jpg",
    detailImageUrls: ["/placeholder-detail-16-1.jpg"],
  },
];
